
services:
  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env
    volumes:
      - .:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    command: npm start
    depends_on:
      - api
    restart: always

  api:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - .:/backend
      - /backend/node_modules
    ports:
      - 5000:5000

      - 9229:9229
    command: node server.js
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:17.4
    container_name: mydb2
    build: .
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
